[package]
name = "malware_bazaar_api"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11.17", features = ["blocking", "json", "serde_json"] }
serde = { version = "1.0.163", features = ["serde_derive", "derive"] }
serde_json = "1.0.96"
